var roomsData = [
  {
    id: 1,
    code: "RM1001",
    title: "Studio nhỏ xinh trung tâm Quận 1 - Gần phố đi bộ Nguyễn Huệ",
    district: "Quận 1",
    ward: "Phường Bến Nghé",
    address: "25 Nguyễn Văn Thủ, Phường Bến Nghé, Quận 1, TP. Hồ Chí Minh",
    price: 6200000,
    area: 28,
    type: "Studio",
    image: "images/room1/1.jpg",
    images: [
      "images/room1/1.jpg",
      "images/room1/2.jpg",
      "images/room1/3.jpg"
    ],
    utilities: ["Máy lạnh", "WC riêng", "Kệ bếp", "Thang máy", "Máy giặt", "Không chung chủ"],
    suitableFor: ["Nhân viên văn phòng", "Cặp đôi"],
    status: "Còn phòng",
    description: "Studio nằm ngay khu trung tâm, thuận tiện đi làm, đi học và vui chơi. Phòng có không gian riêng tư, đầy đủ tiện ích cơ bản, phù hợp người đi làm cần chỗ ở sạch đẹp.",
    ownerName: "Anh Tuấn",
    ownerPhone: "0901 234 567"
  },
  {
    id: 2,
    code: "RM1002",
    title: "Căn hộ mini có ban công - Khu Thảo Điền",
    district: "Quận 2",
    ward: "Phường Thảo Điền",
    address: "48 Đường số 64, Phường Thảo Điền, Quận 2, TP. Hồ Chí Minh",
    price: 5800000,
    area: 30,
    type: "Căn hộ mini",
    image: "images/room2/1.jpg",
    images: [
      "images/room2/1.jpg",
      "images/room2/2.jpg",
      "images/room2/3.jpg"
    ],
    utilities: ["Máy lạnh", "WC riêng", "Kệ bếp", "Ban công", "Thang máy", "Bảo vệ"],
    suitableFor: ["Nhân viên văn phòng", "Người nước ngoài", "Cặp đôi"],
    status: "Còn phòng",
    description: "Căn hộ mini có ban công thoáng, nằm trong khu dân cư yên tĩnh. Khu vực nhiều quán cà phê, siêu thị và tiện ích, phù hợp với người thích môi trường sống hiện đại.",
    ownerName: "Chị Hạnh",
    ownerPhone: "0932 456 789"
  },
  {
    id: 3,
    code: "RM1003",
    title: "Phòng trọ tiện nghi gần Hồ Con Rùa - Quận 3",
    district: "Quận 3",
    ward: "Phường 6",
    address: "112 Võ Văn Tần, Phường 6, Quận 3, TP. Hồ Chí Minh",
    price: 4300000,
    area: 24,
    type: "Phòng trọ",
    image: "images/room3/1.jpg",
    images: [
      "images/room3/1.jpg",
      "images/room3/2.jpg",
      "images/room3/3.jpg"
    ],
    utilities: ["Máy lạnh", "WC riêng", "Kệ bếp", "Giờ giấc tự do", "Không chung chủ"],
    suitableFor: ["Sinh viên", "Nhân viên văn phòng"],
    status: "Còn phòng",
    description: "Phòng trọ nằm gần trung tâm Quận 3, dễ di chuyển sang Quận 1, Quận 10 và Bình Thạnh. Phòng sạch sẽ, có bếp nhỏ và nhà vệ sinh riêng.",
    ownerName: "Anh Hoàng",
    ownerPhone: "0918 888 999"
  },
  {
    id: 4,
    code: "RM1004",
    title: "Studio gần cầu Calmette - Thuận tiện sang Quận 1",
    district: "Quận 4",
    ward: "Phường 12",
    address: "76 Đoàn Văn Bơ, Phường 12, Quận 4, TP. Hồ Chí Minh",
    price: 3900000,
    area: 25,
    type: "Studio",
    image: "images/room4/1.jpg",
    images: [
      "images/room4/1.jpg",
      "images/room4/2.jpg",
      "images/room4/3.jpg"
    ],
    utilities: ["Máy lạnh", "WC riêng", "Kệ bếp", "Máy giặt", "Giờ giấc tự do"],
    suitableFor: ["Sinh viên", "Nhân viên văn phòng", "Cặp đôi"],
    status: "Còn phòng",
    description: "Studio nhỏ gọn, phù hợp với người cần di chuyển thường xuyên sang trung tâm. Khu vực nhiều hàng quán, chợ và cửa hàng tiện lợi.",
    ownerName: "Chị Ngọc",
    ownerPhone: "0987 654 321"
  },
  {
    id: 5,
    code: "RM1005",
    title: "Phòng trọ gần Đại học Y Dược - Quận 5",
    district: "Quận 5",
    ward: "Phường 11",
    address: "210 Hồng Bàng, Phường 11, Quận 5, TP. Hồ Chí Minh",
    price: 3300000,
    area: 22,
    type: "Phòng trọ",
    image: "images/room5/1.jpg",
    images: [
      "images/room5/1.jpg",
      "images/room5/2.jpg",
      "images/room5/3.jpg"
    ],
    utilities: ["Máy lạnh", "WC riêng", "Kệ bếp", "Không chung chủ"],
    suitableFor: ["Sinh viên", "Người đi làm"],
    status: "Còn phòng",
    description: "Phòng trọ phù hợp sinh viên khu vực Quận 5, gần trường học, bệnh viện và chợ. Không gian vừa đủ, có cửa sổ và nhà vệ sinh riêng.",
    ownerName: "Cô Thảo",
    ownerPhone: "0907 555 666"
  },
  {
    id: 6,
    code: "RM1006",
    title: "Phòng trọ giá tốt gần chợ Bình Tây - Quận 6",
    district: "Quận 6",
    ward: "Phường 2",
    address: "35 Minh Phụng, Phường 2, Quận 6, TP. Hồ Chí Minh",
    price: 2800000,
    area: 20,
    type: "Phòng trọ",
    image: "images/room6/1.jpg",
    images: [
      "images/room6/1.jpg",
      "images/room6/2.jpg",
      "images/room6/3.jpg"
    ],
    utilities: ["WC riêng", "Gác lửng", "Giờ giấc tự do", "Không chung chủ"],
    suitableFor: ["Sinh viên", "Người đi làm"],
    status: "Còn phòng",
    description: "Phòng trọ giá mềm, thích hợp cho người muốn tiết kiệm chi phí. Khu vực gần chợ, siêu thị và các tuyến đường lớn.",
    ownerName: "Chú Minh",
    ownerPhone: "0935 222 111"
  },
  {
    id: 7,
    code: "RM1007",
    title: "Căn hộ mini gần Lotte Mart Quận 7",
    district: "Quận 7",
    ward: "Phường Tân Phong",
    address: "512 Lâm Văn Bền, Phường Tân Phong, Quận 7, TP. Hồ Chí Minh",
    price: 4200000,
    area: 26,
    type: "Căn hộ mini",
    image: "images/room7/1.jpg",
    images: [
      "images/room7/1.jpg",
      "images/room7/2.jpg",
      "images/room7/3.jpg"
    ],
    utilities: ["Máy lạnh", "WC riêng", "Kệ bếp", "Thang máy", "Máy giặt", "Không chung chủ"],
    suitableFor: ["Sinh viên", "Nhân viên văn phòng", "Cặp đôi"],
    status: "Còn phòng",
    description: "Căn hộ mini nằm gần trung tâm thương mại, trường đại học và khu dân cư đông đúc. Phòng có bếp riêng, phù hợp với người thích sự riêng tư.",
    ownerName: "Anh Minh",
    ownerPhone: "0909 999 888"
  },
  {
    id: 8,
    code: "RM1008",
    title: "Phòng trọ rộng gần cầu Chữ Y - Quận 8",
    district: "Quận 8",
    ward: "Phường 5",
    address: "90 Phạm Hùng, Phường 5, Quận 8, TP. Hồ Chí Minh",
    price: 3000000,
    area: 23,
    type: "Phòng trọ",
    image: "images/room8/1.jpg",
    images: [
      "images/room8/1.jpg",
      "images/room8/2.jpg",
      "images/room8/3.jpg"
    ],
    utilities: ["Máy lạnh", "WC riêng", "Gác lửng", "Kệ bếp", "Giờ giấc tự do"],
    suitableFor: ["Sinh viên", "Người đi làm"],
    status: "Còn phòng",
    description: "Phòng trọ có diện tích khá rộng, có gác lửng và khu nấu ăn nhỏ. Vị trí dễ đi sang Quận 5, Quận 7 và Quận 1.",
    ownerName: "Chị Mai",
    ownerPhone: "0966 555 444"
  },
  {
    id: 9,
    code: "RM1009",
    title: "Studio gần khu công nghệ cao - Quận 9",
    district: "Quận 9",
    ward: "Phường Tăng Nhơn Phú A",
    address: "44 Lê Văn Việt, Phường Tăng Nhơn Phú A, Quận 9, TP. Hồ Chí Minh",
    price: 3500000,
    area: 25,
    type: "Studio",
    image: "images/room9/1.jpg",
    images: [
      "images/room9/1.jpg",
      "images/room9/2.jpg",
      "images/room9/3.jpg"
    ],
    utilities: ["Máy lạnh", "WC riêng", "Kệ bếp", "Ban công", "Không chung chủ"],
    suitableFor: ["Sinh viên", "Nhân viên văn phòng"],
    status: "Còn phòng",
    description: "Studio phù hợp sinh viên và nhân viên làm việc tại khu công nghệ cao. Không gian sáng, có ban công nhỏ và khu bếp riêng.",
    ownerName: "Anh Khoa",
    ownerPhone: "0908 777 666"
  },
  {
    id: 10,
    code: "RM1010",
    title: "Phòng trọ gần Đại học Bách Khoa - Quận 10",
    district: "Quận 10",
    ward: "Phường 14",
    address: "62 Tô Hiến Thành, Phường 14, Quận 10, TP. Hồ Chí Minh",
    price: 3400000,
    area: 22,
    type: "Phòng trọ",
    image: "images/room10/1.jpg",
    images: [
      "images/room10/1.jpg",
      "images/room10/2.jpg",
      "images/room10/3.jpg"
    ],
    utilities: ["Máy lạnh", "WC riêng", "Gác lửng", "Không chung chủ", "Giờ giấc tự do"],
    suitableFor: ["Sinh viên", "Người đi làm"],
    status: "Còn phòng",
    description: "Phòng trọ gần trường đại học, trung tâm thương mại và khu ăn uống. Phù hợp sinh viên cần nơi ở tiện lợi, dễ di chuyển.",
    ownerName: "Chị Oanh",
    ownerPhone: "0945 123 789"
  },
  {
    id: 11,
    code: "RM1011",
    title: "Phòng trọ sạch sẽ gần Đầm Sen - Quận 11",
    district: "Quận 11",
    ward: "Phường 3",
    address: "120 Lạc Long Quân, Phường 3, Quận 11, TP. Hồ Chí Minh",
    price: 3100000,
    area: 21,
    type: "Phòng trọ",
    image: "images/room11/1.jpg",
    images: [
      "images/room11/1.jpg",
      "images/room11/2.jpg",
      "images/room11/3.jpg"
    ],
    utilities: ["Máy lạnh", "WC riêng", "Kệ bếp", "Giờ giấc tự do"],
    suitableFor: ["Sinh viên", "Người đi làm"],
    status: "Còn phòng",
    description: "Phòng trọ nằm trong hẻm yên tĩnh, gần công viên và khu mua sắm. Có toilet riêng, bếp nhỏ và chỗ để xe.",
    ownerName: "Cô Lan",
    ownerPhone: "0977 222 333"
  },
  {
    id: 12,
    code: "RM1012",
    title: "Căn hộ mini gần công viên phần mềm Quang Trung - Quận 12",
    district: "Quận 12",
    ward: "Phường Tân Chánh Hiệp",
    address: "89 Tô Ký, Phường Tân Chánh Hiệp, Quận 12, TP. Hồ Chí Minh",
    price: 3200000,
    area: 24,
    type: "Căn hộ mini",
    image: "images/room12/1.jpg",
    images: [
      "images/room12/1.jpg",
      "images/room12/2.jpg",
      "images/room12/3.jpg"
    ],
    utilities: ["Máy lạnh", "WC riêng", "Kệ bếp", "Máy giặt", "Không chung chủ"],
    suitableFor: ["Sinh viên", "Nhân viên văn phòng"],
    status: "Còn phòng",
    description: "Căn hộ mini có giá vừa phải, gần khu công nghệ và trường học. Phòng phù hợp với người đi làm hoặc sinh viên muốn thuê dài hạn.",
    ownerName: "Anh Quân",
    ownerPhone: "0333 444 555"
  },
  {
    id: 13,
    code: "RM1013",
    title: "Studio có ban công gần Pearl Plaza - Bình Thạnh",
    district: "Bình Thạnh",
    ward: "Phường 21",
    address: "56 Ung Văn Khiêm, Phường 21, Bình Thạnh, TP. Hồ Chí Minh",
    price: 4600000,
    area: 28,
    type: "Studio",
    image: "images/room13/1.jpg",
    images: [
      "images/room13/1.jpg",
      "images/room13/2.jpg",
      "images/room13/3.jpg"
    ],
    utilities: ["Máy lạnh", "WC riêng", "Kệ bếp", "Ban công", "Thang máy", "Máy giặt"],
    suitableFor: ["Sinh viên", "Nhân viên văn phòng", "Cặp đôi"],
    status: "Còn phòng",
    description: "Studio có ban công thoáng, nằm gần các trường đại học và khu văn phòng. Từ phòng có thể di chuyển nhanh sang Quận 1, Quận 2 và Thủ Đức.",
    ownerName: "Anh Sơn",
    ownerPhone: "0906 777 888"
  },
  {
    id: 14,
    code: "RM1014",
    title: "Phòng trọ gần Emart Phan Văn Trị - Gò Vấp",
    district: "Gò Vấp",
    ward: "Phường 8",
    address: "16 Phan Văn Trị, Phường 8, Gò Vấp, TP. Hồ Chí Minh",
    price: 2900000,
    area: 20,
    type: "Phòng trọ",
    image: "images/room14/1.jpg",
    images: [
      "images/room14/1.jpg",
      "images/room14/2.jpg",
      "images/room14/3.jpg"
    ],
    utilities: ["Máy lạnh", "WC riêng", "Gác lửng", "Không chung chủ"],
    suitableFor: ["Sinh viên", "Người đi làm"],
    status: "Còn phòng",
    description: "Phòng trọ có gác lửng, không gian vừa đủ cho 1 đến 2 người. Khu vực gần siêu thị, trường học, quán ăn và tuyến xe buýt.",
    ownerName: "Cô Hoa",
    ownerPhone: "0922 333 444"
  },
  {
    id: 15,
    code: "RM1015",
    title: "Căn hộ mini yên tĩnh gần công viên Gia Định - Phú Nhuận",
    district: "Phú Nhuận",
    ward: "Phường 9",
    address: "88 Hoàng Minh Giám, Phường 9, Phú Nhuận, TP. Hồ Chí Minh",
    price: 4400000,
    area: 26,
    type: "Căn hộ mini",
    image: "images/room15/1.jpg",
    images: [
      "images/room15/1.jpg",
      "images/room15/2.jpg",
      "images/room15/3.jpg"
    ],
    utilities: ["Máy lạnh", "WC riêng", "Kệ bếp", "Thang máy", "Bảo vệ", "Máy giặt"],
    suitableFor: ["Người đi làm", "Cặp đôi"],
    status: "Còn phòng",
    description: "Căn hộ mini nằm trong khu dân cư yên tĩnh, gần công viên và sân bay. Phòng sạch sẽ, có nội thất cơ bản và khu nấu ăn riêng.",
    ownerName: "Chị Vân",
    ownerPhone: "0903 111 222"
  },
  {
    id: 16,
    code: "RM1016",
    title: "Studio cao cấp gần sân bay Tân Sơn Nhất - Tân Bình",
    district: "Tân Bình",
    ward: "Phường 2",
    address: "11 Bạch Đằng, Phường 2, Tân Bình, TP. Hồ Chí Minh",
    price: 5000000,
    area: 31,
    type: "Studio",
    image: "images/room16/1.jpg",
    images: [
      "images/room16/1.jpg",
      "images/room16/2.jpg",
      "images/room16/3.jpg"
    ],
    utilities: ["Máy lạnh", "WC riêng", "Kệ bếp", "Thang máy", "Bảo vệ", "Không chung chủ"],
    suitableFor: ["Nhân viên văn phòng", "Người nước ngoài", "Cặp đôi"],
    status: "Còn phòng",
    description: "Studio gần sân bay, phù hợp người đi làm thường xuyên di chuyển. Phòng có cửa sổ lớn, nội thất cơ bản và hệ thống an ninh tốt.",
    ownerName: "Anh Kiên",
    ownerPhone: "0909 123 456"
  },
  {
    id: 17,
    code: "RM1017",
    title: "Căn hộ mini gần Aeon Mall Tân Phú",
    district: "Tân Phú",
    ward: "Phường Sơn Kỳ",
    address: "19 Bờ Bao Tân Thắng, Phường Sơn Kỳ, Tân Phú, TP. Hồ Chí Minh",
    price: 3800000,
    area: 26,
    type: "Căn hộ mini",
    image: "images/room17/1.jpg",
    images: [
      "images/room17/1.jpg",
      "images/room17/2.jpg",
      "images/room17/3.jpg"
    ],
    utilities: ["Máy lạnh", "WC riêng", "Kệ bếp", "Thang máy", "Máy giặt", "Không chung chủ"],
    suitableFor: ["Sinh viên", "Người đi làm", "Cặp đôi"],
    status: "Còn phòng",
    description: "Căn hộ mini nằm gần trung tâm thương mại, thuận tiện mua sắm, ăn uống và đi lại. Phòng có thiết kế gọn, dễ sinh hoạt.",
    ownerName: "Anh Hải",
    ownerPhone: "0937 777 111"
  },
  {
    id: 18,
    code: "RM1018",
    title: "Phòng trọ mới gần bến xe Miền Tây - Bình Tân",
    district: "Bình Tân",
    ward: "Phường An Lạc",
    address: "102 Kinh Dương Vương, Phường An Lạc, Bình Tân, TP. Hồ Chí Minh",
    price: 2700000,
    area: 20,
    type: "Phòng trọ",
    image: "images/room18/1.jpg",
    images: [
      "images/room18/1.jpg",
      "images/room18/2.jpg",
      "images/room18/3.jpg"
    ],
    utilities: ["WC riêng", "Gác lửng", "Kệ bếp", "Giờ giấc tự do"],
    suitableFor: ["Sinh viên", "Người đi làm"],
    status: "Còn phòng",
    description: "Phòng trọ mới, giá hợp lý, phù hợp người đi làm khu vực Bình Tân. Gần bến xe, siêu thị và nhiều tuyến đường lớn.",
    ownerName: "Chị Yến",
    ownerPhone: "0908 222 333"
  },
  {
    id: 19,
    code: "RM1019",
    title: "Phòng trọ thoáng mát gần chợ Thủ Đức",
    district: "Thủ Đức",
    ward: "Phường Linh Chiểu",
    address: "28 Hoàng Diệu 2, Phường Linh Chiểu, Thủ Đức, TP. Hồ Chí Minh",
    price: 2800000,
    area: 22,
    type: "Phòng trọ",
    image: "images/room19/1.jpg",
    images: [
      "images/room19/1.jpg",
      "images/room19/2.jpg",
      "images/room19/3.jpg"
    ],
    utilities: ["Máy lạnh", "WC riêng", "Kệ bếp", "Không chung chủ"],
    suitableFor: ["Sinh viên", "Người đi làm"],
    status: "Còn phòng",
    description: "Phòng trọ gần chợ Thủ Đức và các trường đại học. Không gian thoáng, có cửa sổ, thích hợp sinh viên thuê lâu dài.",
    ownerName: "Chị Mai",
    ownerPhone: "0912 345 678"
  },
  {
    id: 20,
    code: "RM1020",
    title: "Studio gần Đại học Quốc Gia - Linh Trung",
    district: "Thủ Đức",
    ward: "Phường Linh Trung",
    address: "45 Đường số 8, Phường Linh Trung, Thủ Đức, TP. Hồ Chí Minh",
    price: 3000000,
    area: 23,
    type: "Studio",
    image: "images/room20/1.jpg",
    images: [
      "images/room20/1.jpg",
      "images/room20/2.jpg",
      "images/room20/3.jpg"
    ],
    utilities: ["Máy lạnh", "WC riêng", "Gác lửng", "Giờ giấc tự do", "Không chung chủ"],
    suitableFor: ["Sinh viên"],
    status: "Còn phòng",
    description: "Studio nhỏ gọn, gần khu Đại học Quốc Gia, phù hợp sinh viên. Khu vực có nhiều quán ăn, tiệm photocopy và dịch vụ sinh viên.",
    ownerName: "Bác Hùng",
    ownerPhone: "0356 123 456"
  },
  {
    id: 21,
    code: "RM1021",
    title: "Nhà trọ có gác gần chợ Hóc Môn",
    district: "Hóc Môn",
    ward: "Xã Xuân Thới Đông",
    address: "74 Nguyễn Ảnh Thủ, Xã Xuân Thới Đông, Hóc Môn, TP. Hồ Chí Minh",
    price: 2200000,
    area: 22,
    type: "Phòng trọ",
    image: "images/room21/1.jpg",
    images: [
      "images/room21/1.jpg",
      "images/room21/2.jpg",
      "images/room21/3.jpg"
    ],
    utilities: ["WC riêng", "Gác lửng", "Kệ bếp", "Chỗ để xe"],
    suitableFor: ["Sinh viên", "Công nhân", "Người đi làm"],
    status: "Còn phòng",
    description: "Phòng trọ giá rẻ, có gác lửng và chỗ để xe. Phù hợp người đi làm hoặc sinh viên muốn tiết kiệm chi phí thuê phòng.",
    ownerName: "Chú Bảy",
    ownerPhone: "0907 555 666"
  },
  {
    id: 22,
    code: "RM1022",
    title: "Phòng trọ rộng gần Quốc lộ 1A - Bình Chánh",
    district: "Bình Chánh",
    ward: "Xã Bình Hưng",
    address: "150 Quốc lộ 1A, Xã Bình Hưng, Bình Chánh, TP. Hồ Chí Minh",
    price: 2600000,
    area: 24,
    type: "Phòng trọ",
    image: "images/room22/1.jpg",
    images: [
      "images/room22/1.jpg",
      "images/room22/2.jpg",
      "images/room22/3.jpg"
    ],
    utilities: ["WC riêng", "Gác lửng", "Kệ bếp", "Giờ giấc tự do"],
    suitableFor: ["Công nhân", "Người đi làm", "Gia đình nhỏ"],
    status: "Còn phòng",
    description: "Phòng rộng, phù hợp người đi làm hoặc gia đình nhỏ. Vị trí gần các tuyến đường lớn, dễ di chuyển sang Quận 8, Quận 7 và Bình Tân.",
    ownerName: "Cô Hương",
    ownerPhone: "0968 888 777"
  },
  {
    id: 23,
    code: "RM1023",
    title: "Căn hộ mini gần khu dân cư Nhà Bè",
    district: "Nhà Bè",
    ward: "Xã Phước Kiển",
    address: "39 Nguyễn Hữu Thọ, Xã Phước Kiển, Nhà Bè, TP. Hồ Chí Minh",
    price: 3600000,
    area: 27,
    type: "Căn hộ mini",
    image: "images/room23/1.jpg",
    images: [
      "images/room23/1.jpg",
      "images/room23/2.jpg",
      "images/room23/3.jpg"
    ],
    utilities: ["Máy lạnh", "WC riêng", "Kệ bếp", "Ban công", "Máy giặt"],
    suitableFor: ["Sinh viên", "Nhân viên văn phòng", "Cặp đôi"],
    status: "Còn phòng",
    description: "Căn hộ mini có ban công, khu vực yên tĩnh và dễ đi sang Quận 7. Phù hợp với người thích không gian sống thoáng và riêng tư.",
    ownerName: "Anh Nam",
    ownerPhone: "0904 555 666"
  },
  {
    id: 24,
    code: "RM1024",
    title: "Phòng trọ giá rẻ gần khu công nghiệp Củ Chi",
    district: "Củ Chi",
    ward: "Xã Tân Phú Trung",
    address: "88 Tỉnh lộ 8, Xã Tân Phú Trung, Củ Chi, TP. Hồ Chí Minh",
    price: 2000000,
    area: 20,
    type: "Phòng trọ",
    image: "images/room24/1.jpg",
    images: [
      "images/room24/1.jpg",
      "images/room24/2.jpg",
      "images/room24/3.jpg"
    ],
    utilities: ["WC riêng", "Gác lửng", "Chỗ để xe", "Giờ giấc tự do"],
    suitableFor: ["Công nhân", "Người đi làm"],
    status: "Còn phòng",
    description: "Phòng trọ giá tốt, phù hợp công nhân hoặc người đi làm gần khu công nghiệp. Khu trọ có chỗ để xe và lối đi riêng.",
    ownerName: "Chú Tư",
    ownerPhone: "0972 999 888"
  },
  {
    id: 25,
    code: "RM1025",
    title: "Phòng trọ thoáng gần biển Cần Giờ",
    district: "Cần Giờ",
    ward: "Thị trấn Cần Thạnh",
    address: "22 Duyên Hải, Thị trấn Cần Thạnh, Cần Giờ, TP. Hồ Chí Minh",
    price: 1800000,
    area: 22,
    type: "Phòng trọ",
    image: "images/room25/1.jpg",
    images: [
      "images/room25/1.jpg",
      "images/room25/2.jpg",
      "images/room25/3.jpg"
    ],
    utilities: ["WC riêng", "Kệ bếp", "Chỗ để xe", "Không chung chủ"],
    suitableFor: ["Người đi làm", "Gia đình nhỏ"],
    status: "Còn phòng",
    description: "Phòng trọ thoáng mát, phù hợp người làm việc tại khu vực Cần Giờ. Không gian yên tĩnh, giá thuê dễ chịu.",
    ownerName: "Anh Hải",
    ownerPhone: "0937 777 111"
  },
  {
    id: 26,
    code: "RM1026",
    title: "Duplex nhỏ xinh gần Landmark 81 - Bình Thạnh",
    district: "Bình Thạnh",
    ward: "Phường 22",
    address: "42 Nguyễn Hữu Cảnh, Phường 22, Bình Thạnh, TP. Hồ Chí Minh",
    price: 5600000,
    area: 35,
    type: "Duplex",
    image: "images/room26/1.jpg",
    images: [
      "images/room26/1.jpg",
      "images/room26/2.jpg",
      "images/room26/3.jpg"
    ],
    utilities: ["Máy lạnh", "WC riêng", "Kệ bếp", "Ban công", "Thang máy", "Bảo vệ", "Máy giặt"],
    suitableFor: ["Nhân viên văn phòng", "Cặp đôi"],
    status: "Còn phòng",
    description: "Duplex có thiết kế hiện đại, phù hợp người đi làm tại khu vực trung tâm. Phòng có gác cao, khu sinh hoạt riêng và ánh sáng tốt.",
    ownerName: "Anh Phúc",
    ownerPhone: "0938 111 222"
  },
  {
    id: 27,
    code: "RM1027",
    title: "Ở ghép căn hộ 3PN Phú Mỹ Hưng - Quận 7",
    district: "Quận 7",
    ward: "Phường Tân Hưng",
    address: "89 Đường số 9, Phường Tân Hưng, Quận 7, TP. Hồ Chí Minh",
    price: 2300000,
    area: 90,
    type: "Ở ghép",
    image: "images/room27/1.jpg",
    images: [
      "images/room27/1.jpg",
      "images/room27/2.jpg",
      "images/room27/3.jpg"
    ],
    utilities: ["Máy lạnh", "WC riêng", "Kệ bếp", "Ban công", "Thang máy", "Bảo vệ", "Máy giặt"],
    suitableFor: ["Sinh viên", "Người đi làm"],
    status: "Còn phòng",
    description: "Căn hộ ở ghép có phòng riêng, khu bếp và phòng khách dùng chung. Phù hợp sinh viên hoặc người đi làm muốn ở khu vực an ninh, tiện nghi.",
    ownerName: "Bạn Như",
    ownerPhone: "0345 123 789"
  },
  {
    id: 28,
    code: "RM1028",
    title: "Studio gần Đại học Văn Lang cơ sở Gò Vấp",
    district: "Gò Vấp",
    ward: "Phường 5",
    address: "566 Nguyễn Thái Sơn, Phường 5, Gò Vấp, TP. Hồ Chí Minh",
    price: 3700000,
    area: 25,
    type: "Studio",
    image: "images/room28/1.jpg",
    images: [
      "images/room28/1.jpg",
      "images/room28/2.jpg",
      "images/room28/3.jpg"
    ],
    utilities: ["Máy lạnh", "WC riêng", "Kệ bếp", "Thang máy", "Máy giặt"],
    suitableFor: ["Sinh viên", "Nhân viên văn phòng"],
    status: "Còn phòng",
    description: "Studio gần trường đại học, phù hợp sinh viên cần nơi ở sạch sẽ, riêng tư. Khu vực nhiều quán ăn, cửa hàng tiện lợi và tuyến xe buýt.",
    ownerName: "Chị Trâm",
    ownerPhone: "0902 666 555"
  },
  {
    id: 29,
    code: "RM1029",
    title: "Phòng trọ gần chợ Tân Định - Quận 1",
    district: "Quận 1",
    ward: "Phường Tân Định",
    address: "72 Hai Bà Trưng, Phường Tân Định, Quận 1, TP. Hồ Chí Minh",
    price: 4800000,
    area: 24,
    type: "Phòng trọ",
    image: "images/room29/1.jpg",
    images: [
      "images/room29/1.jpg",
      "images/room29/2.jpg",
      "images/room29/3.jpg"
    ],
    utilities: ["Máy lạnh", "WC riêng", "Kệ bếp", "Máy giặt", "Không chung chủ"],
    suitableFor: ["Nhân viên văn phòng", "Sinh viên"],
    status: "Còn phòng",
    description: "Phòng trọ nằm trong khu trung tâm nhưng hẻm yên tĩnh. Phù hợp người đi làm hoặc sinh viên muốn ở gần Quận 3, Bình Thạnh và Phú Nhuận.",
    ownerName: "Anh Long",
    ownerPhone: "0919 121 212"
  },
  {
    id: 30,
    code: "RM1030",
    title: "Căn hộ mini gần Vincom Thủ Đức",
    district: "Thủ Đức",
    ward: "Phường Linh Tây",
    address: "101 Võ Văn Ngân, Phường Linh Tây, Thủ Đức, TP. Hồ Chí Minh",
    price: 4000000,
    area: 27,
    type: "Căn hộ mini",
    image: "images/room30/1.jpg",
    images: [
      "images/room30/1.jpg",
      "images/room30/2.jpg",
      "images/room30/3.jpg"
    ],
    utilities: ["Máy lạnh", "WC riêng", "Kệ bếp", "Thang máy", "Máy giặt", "Không chung chủ"],
    suitableFor: ["Sinh viên", "Nhân viên văn phòng", "Cặp đôi"],
    status: "Còn phòng",
    description: "Căn hộ mini gần trung tâm Thủ Đức, thuận tiện đi học, đi làm và sinh hoạt. Phòng có nội thất cơ bản, bếp riêng và toilet khép kín.",
    ownerName: "Anh Tín",
    ownerPhone: "0915 678 999"
  }
];

window.roomsData = roomsData;
window.rooms = roomsData;